version: "3.9"

services:
  web-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: K0rmaVindal00!!
      POSTGRES_DB: StarTrekWeatherDB
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./StarTrekWeather/StarTrekWeather_create.sql:/docker-entrypoint-initdb.d/StarTrekWeather_create.sql


  web:
    build: 
      context: ./StarTrekWeather
      dockerfile: Dockerfile
    depends_on:
      - web-db
    environment:
      ConnectionStrings__DefaultConnection: "Host=web-db;Port=5432;Database=StarTrekWeatherDB;Username=postgres;Password=K0rmaVindal00!!"
    ports:
      - "5001:80"
        
  api:
    build:
      context: ./StarTrekWeather.Api
      dockerfile: Dockerfile
    ports:
      - "5002:8080"

volumes:
  pg_data: